services:
    david63.mergeusers.admin.controller:
        class: david63\mergeusers\controller\admin_controller
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@log'			
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@language'
            - '@david63.mergeusers.core.functions'
            - '%tables%'

    david63.mergeusers.core.functions:
        class: david63\mergeusers\core\functions
        arguments:
            - '@ext.manager'

    _defaults:
        public: true
